version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.3-browsers

        steps:
            - checkout

            - run:
                name: Install dependencies
                command: |
                    sudo apt update
                    sudo docker-php-ext-install zip
                    sudo apt-get install sqlite3
                    sudo apt-get install php7.3-sqlite
                    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                    chmod +x ./cc-test-reporter

            #- run:
            #    name: Setup test database
            #    command: |
            #        sqlite3 data/test_placeholder.sqlite < sql/ddl/test_sqlite.sql
            #        chmod 666 data/test_placeholder.sqlite

            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "composer.json" }}
                - v1-dependencies-

            - run: make install

            - save_cache:
                key: v1-dependencies-{{ checksum "composer.json" }}
                paths:
                    - ./vendor

            - run:
                name: Run tests
                command: |
                    ./cc-test-reporter before-build
                    make test
                    ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
